on:
  schedule:
    # 每分钟执行一次
    - cron: '0 0 * * *'

jobs:
  sign-in:
    runs-on: ubuntu-latest
    steps:
      - name: Sign in
        run: |
          curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -d 'token=7161fb770a77b604a15c5e362cdadc9a&guid=10611' https://m300wxapp.jumpw.com/sign/ing?type=wx
