# name: Daily Sign In
 
# on:
#   schedule:
#     - cron: '52 17 * * *' # 每天早上8点执行
 
# jobs:
#   sign-in:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Sign In
#         run: |
#           URL="https://m300wxapp.jumpw.com/sign/ing?type=wx"
#           TOKEN="token=1010a43d30488e0a08c0f7b50f352980&guid=10611" # 如果需要的话
#           curl -H "Authorization: Bearer $TOKEN" -X POST $URL

name: Sign-in every minute

on:
  schedule:
    # 每分钟执行一次
    - cron: '*/1 * * * *'

jobs:
  sign-in:
    runs-on: ubuntu-latest
    steps:
      - name: Sign in
        run: |
          curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -d '{"token": "1010a43d30488e0a08c0f7b50f352980&guid=10611"}' https://m300wxapp.jumpw.com/sign/ing?type=wx
